
version: '2'

services:
        postgres:
            image: sameersbn/postgresql:9.6-2
            ports:
                - "5432:5432"
            environment:
                - DB_USER=pg
                - DB_PASS=pgpass
